const actions = {
  SET_STATE: 'tweets/SET_STATE',
  GET_TOP_TWEETS: 'tweets/GET_TOP_TWEETS',
  GET_NEW_TWEETS: 'tweets/GET_NEW_TWEETS',
  LOAD_MORE_TWEETS: 'tweets/LOAD_MORE_TWEETS',
  GET_USER_TWEETS: 'tweets/GET_USER_TWEETS',

  FETCH_CURRENT_USER_NEW_TWEETS: 'tweets/FETCH_CURRENT_USER_NEW_TWEETS',
}

export default actions
